name: Python build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]
        os: [ ubuntu-latest ]
        experimental: [ false ]
        include:
          - python: 3.9
            os: windows-latest
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: mkdir
        run: |
          mkdir $HOME/opt

      - name: ZeroMQ 4.2.5 and CZMQ 4.1.1
        run: |
          wget --no-check-certificate "https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz" -O zeromq-4.3.4.tar.gz
          tar xzf zeromq-4.3.4.tar.gz
          ( cd zeromq-4.3.4 && ./configure --without-{libsodium,pgm} && make && sudo make install )
          wget --no-check-certificate "https://github.com/zeromq/czmq/releases/download/v4.2.1/czmq-4.2.1.tar.gz" -O czmq-4.2.1.tar.gz
          tar xzf czmq-4.2.1.tar.gz
          ( cd czmq-4.2.1 && ./configure && make && sudo make install )

      - name: Latest NET-SNMP
        run: |
          wget "http://sourceforge.net/projects/net-snmp/files/net-snmp/5.9.1/net-snmp-5.9.1.tar.gz/download" -O net-snmp-5.9.1.tar.gz
          tar xzf net-snmp-5.9.1.tar.gz
          ( cd net-snmp-5.9.1 && ./configure --enable-ipv6 --with-defaults --disable-embedded-perl --disable-as-needed && make )

      - name: Build
        run: |
          pip install -r requirements.txt
          python setup.py --basedir=./net-snmp-5.9.1 --libdir=$HOME/opt/lib build_ext -i

      - name: Package
        run: |
          pip install wheel
          python setup.py --basedir=./net-snmp-5.9.1 --libdir=$HOME/opt/lib bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          name: net-snmp-wheels
          path: dist

