name: Windows build
on:
  push:
  pull_request:

jobs:
  nobuild:
    runs-on: windows-2019

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: actions/checkout@v2
      - name: Install wget
        run: choco install wget

      - name: Checkout libzmq
        uses: actions/checkout@v2
        with:
          repository: zeromq/libzmq
          ref: v4.3.4
          path: libzmq

      - name: Checkout czmq
        uses: actions/checkout@v2
        with:
          repository: zeromq/czmq
          ref: v4.2.1
          path: czmq

      - name: Get NET-SNMP
        run: |
          wget "https://sourceforge.net/projects/net-snmp/files/net-snmp/5.9.1/net-snmp-5.9.1.tar.gz/download" -O net-snmp-5.9.1.tar.gz
          tar xzf net-snmp-5.9.1.tar.gz -C ${{ github.workspace }}

      - name: Copy files
        run: |
          dir net-snmp-5.9.1
          cp -r ${{ github.workspace }}/net-snmp-5.9.1/win32/net-snmp/ ${{ github.workspace }}/netsnmp/net-snmp
          cp -r ${{ github.workspace }}/net-snmp-5.9.1/include/net-snmp/* ${{ github.workspace }}/netsnmp/net-snmp
          dir ${{ github.workspace }}/netsnmp/net-snmp

      - name: Python build
        run: |
          python setup.py build_ext