name: Windows build
on:
  push:
  pull_request:

jobs:
  nobuild:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc, mingw32]

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: actions/checkout@v2
      - name: Install wget
        run: choco install wget

      - name: Checkout libzmq
        uses: actions/checkout@v2
        with:
          repository: zeromq/libzmq
          ref: v4.3.4
          path: libzmq

      - name: Checkout czmq
        uses: actions/checkout@v2
        with:
          repository: zeromq/czmq
          ref: v4.2.1
          path: czmq

      - name: Get NET-SNMP
        run: |
          wget "https://sourceforge.net/projects/net-snmp/files/net-snmp/5.9.1/net-snmp-5.9.1.tar.gz/download" -O net-snmp-5.9.1.tar.gz
          tar xzf net-snmp-5.9.1.tar.gz -C ${{ github.workspace }}
          mv net-snmp-5.9.1 net-snmp
          cp ${{ github.workspace }}/net-snmp/win32/net-snmp/net-snmp-config.h ${{ github.workspace }}/net-snmp/include/net-snmp
          cp ${{ github.workspace }}/net-snmp/win32/net-snmp/library/snmpv3-security-includes.h ${{ github.workspace }}/net-snmp/include/net-snmp/library

      - name: Python build
        shell: bash
        run: |
          python setup_windows.py build_ext --basedir="${{ github.workspace }}/net-snmp" --include-dirs="${{ github.workspace }}/net-snmp/include;${{ github.workspace }}/libzmq/include;${{ github.workspace }}/czmq/include" -c ${{ matrix.compiler }}