name: Windows build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Install wget
        run: choco install wget

      - name: Configure ZeroMQ
        run: |
          bash configure_zeromq.sh

      - name: Make ZeroMQ
        shell: cmd
        run: |
          cd zeromq-4.3.4
          cmake -G "NMake Makefiles" -D WITH_PERF_TOOL=OFF -D ZMQ_BUILD_TESTS=OFF -D ENABLE_CPACK=OFF -D CMAKE_BUILD_TYPE=Release
