name: Windows build multiple jobs
on:
  push:
  pull_request:

jobs:
  build_zeromq:
    name: Build ZeroMQ
    runs-on: windows-2019
    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout libzmq
        uses: actions/checkout@v2
        with:
          repository: zeromq/libzmq
          ref: v4.3.4
          path: libzmq

      - name: Make ZeroMQ
        run: |
          cd libzmq
          mkdir build
          cd build
          cmake .. -DBUILD_STATIC=ON -DBUILD_SHARED=ON -DZMQ_BUILD_TESTS=OFF -DWITH_LIBSODIUM=OFF -DCMAKE_INSTALL_PREFIX=C:\libzmq
          cmake --build . --config Release --target install

      - name: Upload ZeroMQ installation
        uses: actions/upload-artifact@v2
        with:
          name: zeromq-install
          path: C:\libzmq

      - name: Package source
        working-directory: ${{ github.workspace }}
        run: tar -czf libzmq.tgz libzmq

      - name: Upload ZeroMQ source folder
        uses: actions/upload-artifact@v2
        with:
          name: zeromq-source
          path: ${{ github.workspace }}/libzmq.tgz

  build_czmq:
    runs-on: windows-2019
    name: Build CZMQ
    needs: build_zeromq

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Download ZeroMQ installation
        uses: actions/download-artifact@v2
        with:
          name: zeromq-install
          path: C:\libzmq

      - name: Checkout czmq
        uses: actions/checkout@v2
        with:
          repository: zeromq/czmq
          ref: v4.2.1
          path: czmq

      - name: Make czmq
        run: |
          cd czmq
          mkdir build
          cd build
          cmake .. -DCZMQ_BUILD_SHARED=ON -DCZMQ_BUILD_STATIC=ON -DCMAKE_PREFIX_PATH=C:\libzmq -DCMAKE_INSTALL_PREFIX=C:\czmq
          cmake --build . --config Release --target install

      - name: Upload CZMQ installation
        uses: actions/upload-artifact@v2
        with:
          name: czmq-install
          path: C:\czmq

      - name: Package source
        working-directory: ${{ github.workspace }}
        run: tar -czf czmq.tgz czmq

      - name: Upload CZMQ source folder
        uses: actions/upload-artifact@v2
        with:
          name: czmq-source
          path: ${{ github.workspace }}/czmq.tgz

  build_netsnmp:
    name: Build NET-SNMP
    runs-on: windows-2019
    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Checkout net-snmp
        uses: actions/checkout@v2
        with:
          repository: net-snmp/net-snmp
          ref: v5.9.1
          path: net-snmp

      - name: Configure NET-SNMP
        working-directory: ${{ github.workspace }}/net-snmp/win32
        run: perl Configure --config=release --with-sdk --linktype=static --prefix ${{ github.workspace }}/netsmp_build

      - name: Make NET-SNMP
        working-directory: ${{ github.workspace }}/net-snmp/win32
        run: |
          nmake libsnmp
          cp ${{ github.workspace }}/net-snmp/win32/net-snmp/net-snmp-config.h ${{ github.workspace }}/net-snmp/include/net-snmp
          cp ${{ github.workspace }}/net-snmp/win32/net-snmp/library/snmpv3-security-includes.h ${{ github.workspace }}/net-snmp/include/net-snmp/library

      - uses: actions/upload-artifact@v2
        name: Upload NET-SNMP
        with:
          name: netsnmp
          path: |
            ${{ github.workspace }}/net-snmp/include
            ${{ github.workspace }}/net-snmp/win32/lib/release

  build_python:
    name: Build Python package
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    needs:
      - build_zeromq
      - build_czmq
      - build_netsnmp

    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download ZeroMQ folder
        uses: actions/download-artifact@v2
        with:
          name: zeromq-install
          path: ${{ github.workspace }}/libzmq

      - uses: actions/download-artifact@v2
        name: Download czmq
        with:
          name: czmq-install
          path: ${{ github.workspace }}/czmq

      - uses: actions/download-artifact@v2
        name: Download NET-SNMP
        with:
          name: netsnmp
          path: ${{ github.workspace }}/net-snmp

      - name: Patch CZMQ
        working-directory: ${{ github.workspace }}/czmq
        run: patch include/czmq_prelude.h -i ${{ github.workspace }}\uint32_t.patch

      - name: Rename ZeroMQ lib
        working-directory: ${{ github.workspace }}/libzmq
        run: cp lib\libzmq-v142-mt-s-4_3_4.lib lib\zmq.lib

      - name: Python build
        shell: cmd
        run: |
          python setup_windows.py build_ext --include-dirs="${{ github.workspace }}/net-snmp/include;${{ github.workspace }}/libzmq/include;${{ github.workspace }}/czmq/include" --library-dirs=${{ github.workspace }}/libzmq/lib;${{ github.workspace }}/czmq/lib;${{ github.workspace }}/net-snmp/win32/lib/release;${{ github.workspace }}/net-snmp/agent;${{ github.workspace }}/net-snmp/snmplib -D WIN32 -D ZMQ_DEFINED_STDINT

      - name: Package
        run: |
          cp libzmq\bin\libzmq-v142-mt-4_3_4.dll netsnmp
          cp czmq\bin\libczmq.dll netsnmp
          pip install wheel
          python setup_windows.py bdist_wheel

      - name: Custom package
        shell: bash
        run: |
          mkdir -p build_custom/netsnmp
          cp -R czmq build_custom/netsnmp
          cp -R netsnmp build_custom/netsnmp
          cp -R libzmq build_custom/netsnmp
          cp -R net-snmp build_custom/netsnmp
          cd build_custom
          tar -cvzf netsnmp-py${{ matrix.python-version }}.tgz netsnmp

      - uses: actions/upload-artifact@v2
        name: Upload tgz
        with:
          name: build_custom
          path: build_custom/netsnmp-py${{ matrix.python-version }}.tgz

      - uses: actions/upload-artifact@v2
        with:
          name: net-snmp-wheels
          path: dist

  test_wheel:
    name: Test wheel
    runs-on: windows-2019

    needs: build_python

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
      - uses: actions/download-artifact@v2
        name: Download wheel
        with:
          name: net-snmp-wheels
          path: wheels

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install wheel for Python 3.7
        if: ${{ matrix.python-version == 3.7 }}
        run: pip install ${{ github.workspace }}\wheels\netsnmp_py-0.5.2-cp37-cp37-win_amd64.whl

      - name: Install wheel for Python 3.8
        if: ${{ matrix.python-version == 3.8 }}
        run: pip install ${{ github.workspace }}\wheels\netsnmp_py-0.5.2-cp38-cp38-win_amd64.whl

      - name: Install wheel for Python 3.9
        if: ${{ matrix.python-version == 3.9 }}
        run: pip install ${{ github.workspace }}\wheels\netsnmp_py-0.5.2-cp39-cp39-win_amd64.whl

      - uses: actions/checkout@v2
        with:
          path: project

      - name: Copy files
        shell: bash
        run: |
          cp project test_api.py .
          cp project test_async.py .

      - name: Run API test
        run: python test_api.py

      - name: Run async test
        run: python test_async.py