name: Windows build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Install wget
        run: choco install wget

      - name: Configure ZeroMQ
        run: |
          bash configure_zeromq.sh

      - name: Make ZeroMQ
        shell: cmd
        run: |
          cd zeromq-4.3.4
          make
          make install